### ISSUE TITLE
XCode fails to build if Sentry is disabled

### ISSUE THREAD

**Issue by astro75** [getsentry/sentry-unity#1324]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which version of the SDK?
1.2.0

How did you install the package? 
Git-URL

Which version of Unity?
2022.2.19f1

Is this happening in Unity (editor) or on a player like Android, iOS, Windows?
Happens while building iOS builds.

### Steps to Reproduce

1. Uncheck `Enable Sentry` checkbox in Unity Sentry Settings window.
2. Build ios build.

### Expected Result

Build succeeds, like in all other platforms.

### Actual Result

Xcode build fails with an exception

### Any logs or screenshots

```❌ Undefined symbols for architecture arm64
❌   "_SentryNativeBridgeAddBreadcrumb", referenced from:
⚠️       _NativeScopeObserver_AddBreadcrumbImpl_m4936C3C3E5871A9F276E30515ED7CC5DCDC085CA in libGameAssembly.a(on3abcd9l9qg.o)
⚠️       _SentryCocoaBridgeProxy_SentryNativeBridgeAddBreadcrumb_m1695455F9D3B2AFEE50B0E182393C784629BFA20 in libGameAssembly.a(on3abcd9l9qg.o)
❌   "_SentryNativeBridgeClose", referenced from:
⚠️       _SentryCocoaBridgeProxy_Close_mCA858CBC8513F4E271DD6B96F960A1448BA30C60 in libGameAssembly.a(on3abcd9l9qg.o)
⚠️       _SentryNativeCocoa_Close_mF418EFB979EB67F69603102D173D27E283CA5DDF in libGameAssembly.a(on3abcd9l9qg.o)
⚠️       _U3CU3Ec__DisplayClass1_0_U3CConfigureU3Eb__1_m2F595D37676323847FEBFC97559A5A697D8D756C in libGameAssembly.a(on3abcd9l9qg.o)
❌   "_SentryNativeBridgeCrashedLastRun", referenced from:
⚠️       _SentryCocoaBridgeProxy_CrashedLastRun_m1CE48AEC5CCFA422230FA84E4775FBEF5B3C23C6 in libGameAssembly.a(on3abcd9l9qg.o)
⚠️       _U3CU3Ec__DisplayClass1_0_U3CConfigureU3Eb__0_mCE2FDA3B28D4404EE030C5983CD7B7AE99FCAC1A in libGameAssembly.a(on3abcd9l9qg.o)
❌   "_SentryNativeBridgeGetInstallationId", referenced from:
⚠️       _SentryCocoaBridgeProxy_GetInstallationId_m6991C2CF26EB6B9E17BBE1F3EB6C44FA54213959 in libGameAssembly.a(on3abcd9l9qg.o)
⚠️       _SentryNativeCocoa_Configure_m4452688A83C1723CF2AF77A64A34B658A444DC1E in libGameAssembly.a(on3abcd9l9qg.o)
❌   "_SentryNativeBridgeLoadLibrary", referenced from:
⚠️       _SentryCocoaBridgeProxy_Init_mFBDF944C84BABAF559BA78940961C8E472C245C8 in libGameAssembly.a(on3abcd9l9qg.o)
⚠️       _SentryCocoaBridgeProxy_LoadLibrary_mFF53271AAB14A5146B606635E762B92A76AB5F72 in libGameAssembly.a(on3abcd9l9qg.o)
❌   "_SentryNativeBridgeOptionsNew", referenced from:
⚠️       _SentryCocoaBridgeProxy_Init_mFBDF944C84BABAF559BA78940961C8E472C245C8 in libGameAssembly.a(on3abcd9l9qg.o)
⚠️       _SentryCocoaBridgeProxy_OptionsNew_mA62F72AFA11F09B2DBAC1EA1DA4AD7BBF0167C3C in libGameAssembly.a(on3abcd9l9qg.o)
❌   "_SentryNativeBridgeOptionsSetInt", referenced from:
⚠️       _SentryCocoaBridgeProxy_Init_mFBDF944C84BABAF559BA78940961C8E472C245C8 in libGameAssembly.a(on3abcd9l9qg.o)
⚠️       _SentryCocoaBridgeProxy_OptionsSetInt_m0360A2615B71982444DDE3A2EA4FFCC302979C20 in libGameAssembly.a(on3abcd9l9qg.o)
❌   "_SentryNativeBridgeOptionsSetString", referenced from:
⚠️       _SentryCocoaBridgeProxy_Init_mFBDF944C84BABAF559BA78940961C8E472C245C8 in libGameAssembly.a(on3abcd9l9qg.o)
⚠️       _SentryCocoaBridgeProxy_OptionsSetString_m168F84BCC22144D93168BB4F86A8DB649F9F2889 in libGameAssembly.a(on3abcd9l9qg.o)
❌   "_SentryNativeBridgeSetExtra", referenced from:
⚠️       _NativeScopeObserver_SetExtraImpl_m07D0962C0A4D3B03D9BB378BBA3DA0B8D6C788C9 in libGameAssembly.a(on3abcd9l9qg.o)
⚠️       _SentryCocoaBridgeProxy_SentryNativeBridgeSetExtra_m11593AEC63512316FD1FBF1623C5DC28ADB83218 in libGameAssembly.a(on3abcd9l9qg.o)
❌   "_SentryNativeBridgeSetTag", referenced from:
⚠️       _NativeScopeObserver_SetTagImpl_mB203B2BE86E5798D9832BD42DECE1046FBDD5F65 in libGameAssembly.a(on3abcd9l9qg.o)
⚠️       _SentryCocoaBridgeProxy_SentryNativeBridgeSetTag_m818F91D38E8E9D6A3736A40A13E8D98D3D8E755A in libGameAssembly.a(on3abcd9l9qg.o)
❌   "_SentryNativeBridgeSetUser", referenced from:
⚠️       _NativeScopeObserver_SetUserImpl_m9893BEDDF68D779BD05040233F9A12213552FE91 in libGameAssembly.a(on3abcd9l9qg.o)
⚠️       _SentryCocoaBridgeProxy_SentryNativeBridgeSetUser_m01B71A9F79E3B8560FE9F4DD5C062610EF1236E4 in libGameAssembly.a(on3abcd9l9qg.o)
❌   "_SentryNativeBridgeStartWithOptions", referenced from:
⚠️       _SentryCocoaBridgeProxy_Init_mFBDF944C84BABAF559BA78940961C8E472C245C8 in libGameAssembly.a(on3abcd9l9qg.o)
⚠️       _SentryCocoaBridgeProxy_StartWithOptions_mE2AF258B3EAD92DCE2291B50B5B6BF82412529E3 in libGameAssembly.a(on3abcd9l9qg.o)
❌   "_SentryNativeBridgeUnsetUser", referenced from:
⚠️       _NativeScopeObserver_UnsetUserImpl_m858AB6008DA4E886C9D916F55F29A2D6A1959D75 in libGameAssembly.a(on3abcd9l9qg.o)
⚠️       _SentryCocoaBridgeProxy_SentryNativeBridgeUnsetUser_mF22A63929DA4F6395447064608E96A5E6ADEF00D in libGameAssembly.a(on3abcd9l9qg.o)
❌   "_SentryNativeBridgeWriteScope", referenced from:
⚠️       _NativeContextWriter_SentryNativeBridgeWriteScope_m2A5F2CF1B53DAD0B23EF51F2AFCDA33D007F8329 in libGameAssembly.a(on3abcd9l9qg.o)
❌ ld: symbol(s) not found for architecture arm64
❌ clang: error: linker command failed with exit code 1 (use -v to see invocation)```

**Comment by astro75** [comment]
Additional info: It worked fine with Sentry Unity plugin version 0.26.0 on Unity 2020.3.40

**Comment by bitsandfoxes** [comment]
Hey @astro75, sorry you're running into issues.
I'm a bit stuck on that one and can't reproduce this locally. Do you make any other modifications to the Xcode project?

**Comment by astro75** [comment]
We export xcode project on windows and build on a mac.
The errors happen, because C# code contains `extern` methods that link to native code in ios `.m` files. When we disable Sentry on Unity asset. C# `extern` functions are still getting compiled, but `.m` files are excluded. That results in a build error.

Sorry, we can't test on an empty project at the moment. As a workaround we enable Sentry on all ios builds.
