### ISSUE TITLE
Sentry fails to build with Unity 2021.2.7f1

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-unity#513]
When trying to `dotnet build` the SDK with 2021.2.7f1 the build [fails](https://github.com/getsentry/sentry-unity/runs/4787438355?check_suite_focus=true) with:

> CSC : error CS1705: Assembly 'UnityEngine.TestRunner' with identity 'UnityEngine.TestRunner, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' which has a higher version than referenced assembly 'netstandard' with identity 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' [/Users/runner/work/sentry-unity/sentry-unity/test/Sentry.Unity.Tests/Sentry.Unity.Tests.csproj]

The reason seems to be that the bump leads to an update of the Rider package:

>                 "com.unity.ide.rider": {
>             -      "version": "1.2.1",
>             +      "version": "3.0.7",
>                     "depth": 0,
>                     "source": "registry",
>                     "dependencies": {
>             -        "com.unity.test-framework": "1.1.1"
>             +        "com.unity.ext.nunit": "1.0.6"
>             +      },
>             +      "url": "https://packages.unity.com"
>             +    }

where they [changed](https://docs.unity3d.com/Packages/com.unity.ide.rider@3.0/changelog/CHANGELOG.html#:~:text=Remove%20implicit%20dependency%20to%20Test%2DFramework%20package) their dependency from the `com.unity.test-framework` to `com.unity.ext.nunit`.

Interesting enough the actual test-framework package also has that custom NUnit package as a dependency:

![Screenshot 2022-01-12 at 13 19 13](https://user-images.githubusercontent.com/25725783/149139106-86ffcab5-ab4b-4cf2-a785-9d84d362e979.png)

**Comment by bruno-garcia** [comment]
When we bump the SDK to ns2.1 to get rid of the TestRunner issue described here, Unity isnt' able to compile our managed DLLs with IL2CPP. Issue was raised with Unity (link to be added here)
